// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'no'
	| 'sv'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	navbar: {
		/**
		 * Wallet
		 */
		wallet: string
		/**
		 * Hugin
		 */
		hugin: string
		/**
		 * Mining
		 */
		mining: string
		/**
		 * Articles
		 */
		articles: string
		/**
		 * About
		 */
		about: string
	}
	footer: {
		/**
		 * Navigation
		 */
		title1: string
		/**
		 * Home
		 */
		home: string
		/**
		 * Wallet
		 */
		wallet: string
		/**
		 * Mining
		 */
		mining: string
		/**
		 * Store
		 */
		store: string
		/**
		 * About
		 */
		about: string
		/**
		 * Articles
		 */
		articles: string
		/**
		 * Stickers
		 */
		stickers: string
		/**
		 * Docs
		 */
		docs: string
	}
	components: {
		hero: {
			/**
			 * DECENTRALIZED PRIVATE COMMUNICATION AND PAYMENT SYSTEM.
			 */
			title: string
			/**
			 * A Nordic Cryptocurrency to secure and simplify our future economic system. Sending and receiving money should not be expensive or slow. We work with open source code that allows you to be involved and improve the communication and money of the future.
			 */
			text: string
		}
		statusBar: {
			/**
			 * Height
			 */
			height: string
			/**
			 * Hashrate
			 */
			hashrate: string
			/**
			 * Nodes
			 */
			nodes: string
		}
		features: {
			/**
			 * Nordic Crypto
			 */
			title1: string
			/**
			 * A growing cryptocurrency from the Nordics, with the vision ensure Nordic excellence in development of secure systems and economic tools.
			 */
			text1: string
			/**
			 * Decentralized
			 */
			title2: string
			/**
			 * Kryptokrona adds value to the region as a robust decentralized payment and communication system. Securing our freedom as citizens.
			 */
			text2: string
			/**
			 * Crypto Community
			 */
			title3: string
			/**
			 * Strong local roots with an understanding of politics, culture & language. A feature that should not be underestimated.
			 */
			text3: string
			/**
			 * A response
			 */
			title4: string
			/**
			 * Kryptokrona launched as an open-source alternative to a digital e-krona/e-krone and the growing cashless society in the Nordics.
			 */
			text4: string
			/**
			 * No middleman
			 */
			title5: string
			/**
			 * The Kryptokrona isn’t dependent on any central bank or server, thus less fragile than today's financial systems.
			 */
			text5: string
			/**
			 * Private
			 */
			title6: string
			/**
			 * The basics of Kryptokrona allow users to stay anonymous by default, to send value and data without being revealed or traced.
			 */
			text6: string
		}
		community: {
			/**
			 * Crypto Community
			 */
			title: string
			/**
			 * Join a fast-growing community of developers and innovators connected all over the world. The project is open-source and maintained by the Community. You can for example make changes to this site, suggest awesome new features, or help us squash bugs. Not a developer? No worries, there's tons of things to
		do!
			 */
			text: string
			/**
			 * Join our privacy first messenger.
			 */
			huginText: string
			/**
			 * Technical questions about our tools? Ask a developer on the Community Discord.
			 */
			discordText: string
			/**
			 * Ask general questions and chat with the worldwide community on Telegram.
			 */
			telegramText: string
			/**
			 * Follow @kryptokrona to get the latest news and updates from across the ecosystem.!
			 */
			twitterText: string
		}
		mining: {
			/**
			 * Mining
			 */
			title: string
			/**
			 * Through what’s known as mining the network looks for Kryptokrona. This mechanism secures the network. You are automatically rewarded by the network for your computer’s work
			 */
			text: string
			/**
			 * Get started
			 */
			button: string
		}
		huginChat: {
			/**
			 * Hide with Hugin
			 */
			title: string
			/**
			 * Hugin Messenger puts your privacy first. By the use of military grade encryption, your messages are safe from the prying eyes of others. Hugin uses the decentralized structure that makes cryptocurrencies work, meaning that the system cannot be taken down or be controlled by any one entity.
			 */
			text: string
			/**
			 * Learn more
			 */
			button: string
		}
		fixedBanner: {
			/**
			 * Join us!
			 */
			button: string
		}
	}
	about: {
		/**
		 * About
		 */
		title: string
		/**
		 * Money for the future
		 */
		subTitle: string
		/**
		 * Kryptokrona exists to secure and simplify our future economic system. Sending and receiving money should not be expensive or slow. We work with open source code that allows you to be involved and improve the money of the future.
		 */
		mainText1: string
		/**
		 * Kryptokrona is a decentralized blockchain based on CryptoNote, which forms the basis for Monero, among others. CryptoNote is a so-called “application layer” protocol further developed by TurtleCoin that enables things like: private transactions, messages and arbitrary data storage, completely decentralized.
		 */
		mainText2: string
		/**
		 * On 2 April 2019, the platform was launched in part as a response to the Riksbank’s digital e-krona for the people’s right to create money and to safeguard the private economy without either commercial or store control.
		 */
		mainText3: string
		/**
		 * Max Supply
		 */
		maxSupply: string
		/**
		 * Current Supply
		 */
		currentSupply: string
		/**
		 * GPU Mining Algorithm
		 */
		title2: string
		/**
		 * We currently running on CryptoNight-Pico, which is a fairer algo than Bitcoin's SHA256 and can even be competently mined on ARM based phones!
		 */
		text2: string
		/**
		 * Blocktime
		 */
		title3: string
		/**
		 * Our network processes new transactions every 90 seconds, in comparison to Bitcoins 10 minute delay.
		 */
		text3: string
		/**
		 * Untraceable
		 */
		title4: string
		/**
		 * XKR transactions make use of ring signatures and stealth addresses to keep prying eyes off of your private transactions!
		 */
		text4: string
		/**
		 * Fungible
		 */
		title5: string
		/**
		 * The Kryptokrona isn’t dependent on our central banks or servers, thus less fragile than todays financial systems.
		 */
		text5: string
		/**
		 * Drama-free
		 */
		title6: string
		/**
		 * Our network reduces the amount of new coins minted with every block, making for a drama-free emission.
		 */
		text6: string
	}
}

export type TranslationFunctions = {
	navbar: {
		/**
		 * Wallet
		 */
		wallet: () => LocalizedString
		/**
		 * Hugin
		 */
		hugin: () => LocalizedString
		/**
		 * Mining
		 */
		mining: () => LocalizedString
		/**
		 * Articles
		 */
		articles: () => LocalizedString
		/**
		 * About
		 */
		about: () => LocalizedString
	}
	footer: {
		/**
		 * Navigation
		 */
		title1: () => LocalizedString
		/**
		 * Home
		 */
		home: () => LocalizedString
		/**
		 * Wallet
		 */
		wallet: () => LocalizedString
		/**
		 * Mining
		 */
		mining: () => LocalizedString
		/**
		 * Store
		 */
		store: () => LocalizedString
		/**
		 * About
		 */
		about: () => LocalizedString
		/**
		 * Articles
		 */
		articles: () => LocalizedString
		/**
		 * Stickers
		 */
		stickers: () => LocalizedString
		/**
		 * Docs
		 */
		docs: () => LocalizedString
	}
	components: {
		hero: {
			/**
			 * DECENTRALIZED PRIVATE COMMUNICATION AND PAYMENT SYSTEM.
			 */
			title: () => LocalizedString
			/**
			 * A Nordic Cryptocurrency to secure and simplify our future economic system. Sending and receiving money should not be expensive or slow. We work with open source code that allows you to be involved and improve the communication and money of the future.
			 */
			text: () => LocalizedString
		}
		statusBar: {
			/**
			 * Height
			 */
			height: () => LocalizedString
			/**
			 * Hashrate
			 */
			hashrate: () => LocalizedString
			/**
			 * Nodes
			 */
			nodes: () => LocalizedString
		}
		features: {
			/**
			 * Nordic Crypto
			 */
			title1: () => LocalizedString
			/**
			 * A growing cryptocurrency from the Nordics, with the vision ensure Nordic excellence in development of secure systems and economic tools.
			 */
			text1: () => LocalizedString
			/**
			 * Decentralized
			 */
			title2: () => LocalizedString
			/**
			 * Kryptokrona adds value to the region as a robust decentralized payment and communication system. Securing our freedom as citizens.
			 */
			text2: () => LocalizedString
			/**
			 * Crypto Community
			 */
			title3: () => LocalizedString
			/**
			 * Strong local roots with an understanding of politics, culture & language. A feature that should not be underestimated.
			 */
			text3: () => LocalizedString
			/**
			 * A response
			 */
			title4: () => LocalizedString
			/**
			 * Kryptokrona launched as an open-source alternative to a digital e-krona/e-krone and the growing cashless society in the Nordics.
			 */
			text4: () => LocalizedString
			/**
			 * No middleman
			 */
			title5: () => LocalizedString
			/**
			 * The Kryptokrona isn’t dependent on any central bank or server, thus less fragile than today's financial systems.
			 */
			text5: () => LocalizedString
			/**
			 * Private
			 */
			title6: () => LocalizedString
			/**
			 * The basics of Kryptokrona allow users to stay anonymous by default, to send value and data without being revealed or traced.
			 */
			text6: () => LocalizedString
		}
		community: {
			/**
			 * Crypto Community
			 */
			title: () => LocalizedString
			/**
			 * Join a fast-growing community of developers and innovators connected all over the world. The project is open-source and maintained by the Community. You can for example make changes to this site, suggest awesome new features, or help us squash bugs. Not a developer? No worries, there's tons of things to
		do!
			 */
			text: () => LocalizedString
			/**
			 * Join our privacy first messenger.
			 */
			huginText: () => LocalizedString
			/**
			 * Technical questions about our tools? Ask a developer on the Community Discord.
			 */
			discordText: () => LocalizedString
			/**
			 * Ask general questions and chat with the worldwide community on Telegram.
			 */
			telegramText: () => LocalizedString
			/**
			 * Follow @kryptokrona to get the latest news and updates from across the ecosystem.!
			 */
			twitterText: () => LocalizedString
		}
		mining: {
			/**
			 * Mining
			 */
			title: () => LocalizedString
			/**
			 * Through what’s known as mining the network looks for Kryptokrona. This mechanism secures the network. You are automatically rewarded by the network for your computer’s work
			 */
			text: () => LocalizedString
			/**
			 * Get started
			 */
			button: () => LocalizedString
		}
		huginChat: {
			/**
			 * Hide with Hugin
			 */
			title: () => LocalizedString
			/**
			 * Hugin Messenger puts your privacy first. By the use of military grade encryption, your messages are safe from the prying eyes of others. Hugin uses the decentralized structure that makes cryptocurrencies work, meaning that the system cannot be taken down or be controlled by any one entity.
			 */
			text: () => LocalizedString
			/**
			 * Learn more
			 */
			button: () => LocalizedString
		}
		fixedBanner: {
			/**
			 * Join us!
			 */
			button: () => LocalizedString
		}
	}
	about: {
		/**
		 * About
		 */
		title: () => LocalizedString
		/**
		 * Money for the future
		 */
		subTitle: () => LocalizedString
		/**
		 * Kryptokrona exists to secure and simplify our future economic system. Sending and receiving money should not be expensive or slow. We work with open source code that allows you to be involved and improve the money of the future.
		 */
		mainText1: () => LocalizedString
		/**
		 * Kryptokrona is a decentralized blockchain based on CryptoNote, which forms the basis for Monero, among others. CryptoNote is a so-called “application layer” protocol further developed by TurtleCoin that enables things like: private transactions, messages and arbitrary data storage, completely decentralized.
		 */
		mainText2: () => LocalizedString
		/**
		 * On 2 April 2019, the platform was launched in part as a response to the Riksbank’s digital e-krona for the people’s right to create money and to safeguard the private economy without either commercial or store control.
		 */
		mainText3: () => LocalizedString
		/**
		 * Max Supply
		 */
		maxSupply: () => LocalizedString
		/**
		 * Current Supply
		 */
		currentSupply: () => LocalizedString
		/**
		 * GPU Mining Algorithm
		 */
		title2: () => LocalizedString
		/**
		 * We currently running on CryptoNight-Pico, which is a fairer algo than Bitcoin's SHA256 and can even be competently mined on ARM based phones!
		 */
		text2: () => LocalizedString
		/**
		 * Blocktime
		 */
		title3: () => LocalizedString
		/**
		 * Our network processes new transactions every 90 seconds, in comparison to Bitcoins 10 minute delay.
		 */
		text3: () => LocalizedString
		/**
		 * Untraceable
		 */
		title4: () => LocalizedString
		/**
		 * XKR transactions make use of ring signatures and stealth addresses to keep prying eyes off of your private transactions!
		 */
		text4: () => LocalizedString
		/**
		 * Fungible
		 */
		title5: () => LocalizedString
		/**
		 * The Kryptokrona isn’t dependent on our central banks or servers, thus less fragile than todays financial systems.
		 */
		text5: () => LocalizedString
		/**
		 * Drama-free
		 */
		title6: () => LocalizedString
		/**
		 * Our network reduces the amount of new coins minted with every block, making for a drama-free emission.
		 */
		text6: () => LocalizedString
	}
}

export type Formatters = {}
