// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'no'
	| 'sv'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	navbar: {
		/**
		 * Wallet
		 */
		wallet: string
		/**
		 * Hugin
		 */
		hugin: string
		/**
		 * Mining
		 */
		mining: string
		/**
		 * Articles
		 */
		articles: string
		/**
		 * About
		 */
		about: string
	}
	footer: {
	}
}

export type TranslationFunctions = {
	navbar: {
		/**
		 * Wallet
		 */
		wallet: () => LocalizedString
		/**
		 * Hugin
		 */
		hugin: () => LocalizedString
		/**
		 * Mining
		 */
		mining: () => LocalizedString
		/**
		 * Articles
		 */
		articles: () => LocalizedString
		/**
		 * About
		 */
		about: () => LocalizedString
	}
	footer: {
	}
}

export type Formatters = {}
