// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * Hi
	 */
	HI: string
	/**
	 * What is Kryptokrona?
	 */
	what_is_kryptokrona: string
}

export type TranslationFunctions = {
	/**
	 * Hi
	 */
	HI: () => LocalizedString
	/**
	 * What is Kryptokrona?
	 */
	what_is_kryptokrona: () => LocalizedString
}

export type Formatters = {}
